version: '3'

# More info at https://hub.docker.com/r/linuxserver/deluge 
services:
  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - shared-downloads:/downloads
    restart: unless-stopped

volumes:
  shared-downloads:
