version: '3'

# More info at https://jellyfin.org/docs
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - 8096:8096
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: unless-stopped
