version: '3'

# More info at https://jellyfin.org/docs
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - 8096:8096/tcp
    environment:
      - TZ=Asia/Kolkata
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - shared_movies:/movies
      - shared_tv:/tv
      - shared_music:/music
      - shared_books:/books
      - shared_downloads:/downloads
    restart: unless-stopped

volumes:
  shared_movies:
  shared_tv:
  shared_music:
  shared_books:
  shared_downloads:
