version: '3'

# More info at https://jellyfin.org/docs
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - 8096:8096/tcp
    environment:
      - TZ=Asia/Kolkata
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - share_movies:/movies
      - share_tv:/tv
      - share_music:/music
      - share_books:/books
      - share_downloads:/downloads
    restart: unless-stopped

volumes:
  share_movies:
    external: true
  share_tv:
    external: true
  share_music:
    external: true
  share_books:
    external: true
  share_downloads:
    external: true
