version: '3'

# More info at https://hub.docker.com/r/linuxserver/lidarr
services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - share_music:/music #optional
      - share_downloads:/downloads #optional
    restart: unless-stopped

volumes:
  share_music:
    external: true
  share_downloads:
    external: true
