version: '3'

# More info at https://github.com/alexta69/metube
services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    ports:
      - 8081:8081
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped
