version: '3'

# More info at https://hub.docker.com/r/linuxserver/radarr
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - shared_movies:/movies #optional
      - shared_downloads:/downloads #optional
    restart: unless-stopped

volumes:
  shared_movies:
  shared_downloads:
