version: '3'

# More info at https://hub.docker.com/r/linuxserver/readarr
services:
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - share_books:/books #optional
      - share_downloads:/downloads #optional
    restart: unless-stopped

volumes:
  share_books:
    external: true
  share_downloads:
    external: true
