version: '3'

# More info at https://hub.docker.com/r/linuxserver/sabnzbd
services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    ports:
      - 8088:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - share_downloads:/downloads #optional
      - share_incomplete-downloads:/incomplete-downloads #optional
    restart: unless-stopped

volumes:
  share_downloads:
    external: true
  share_incomplete-downloads:
