version: '3'

# More info at https://hub.docker.com/r/linuxserver/sonarr
services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - shared-tv:/tv #optional
      - shared-downloads:/downloads #optional
    restart: unless-stopped

volumes:
  shared-tv:
  shared-downloads:
