version: '3'

# More info at https://hub.docker.com/r/linuxserver/sonarr
services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - share_tv:/tv #optional
      - share_downloads:/downloads #optional
    restart: unless-stopped

volumes:
  share_tv:
    external: true
  share_downloads:
    external: true
